services:
  # Nginx 服务
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - static_volume:/gongjuyuan_chat/staticfiles    # 静态文件卷
      - media_volume:/gongjuyuan_chat/media      # 媒体文件卷
      - ./nginx.conf:/etc/nginx/nginx.conf       # 挂载 Nginx 配置
    ports:
      - "9000:9000"  
    networks:
      - app_network
    depends_on:
      - web

  # Django 应用服务
  web:
    build: .
    environment:
      PYTHONPATH: /gongjuyuan_chat
      DJANGO_SETTINGS_MODULE: gongjuyuan_chat.settings  # 适配项目名
      UWSGI_PROCESSES: 4
      UWSGI_THREADS: 2
    restart: always
    volumes:
      - static_volume:/gongjuyuan_chat/staticfiles
      - media_volume:/gongjuyuan_chat/media
      - db_volume:/gongjuyuan_chat/db  # 使用命名卷存储数据库
    networks:
      - app_network


# 网络和卷配置
networks:
  app_network:
    driver: bridge

volumes:
  static_volume:    # 静态文件卷
  media_volume:     # 媒体文件卷
  db_volume:        # 数据库卷
