

services:
  # Nginx 服务（端口调整为 9995，避免与宝塔冲突）
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - static_volume:/gongjuyuan_chat/staticfiles    # 静态文件卷
      - media_volume:/gongjuyuan_chat/media      # 媒体文件卷
      - ./nginx.conf:/etc/nginx/nginx.conf       # 挂载 Nginx 配置
    ports:
      - "9995:80"   # 外部访问 9090，容器内仍用 80
    networks:
      - app_network
    depends_on:
      - web

  # Django 应用服务
  web:
    build: .
    environment:
      PYTHONPATH: /gongjuyuan_chat
      DJANGO_SETTINGS_MODULE: gongjuyuan_chat.settings  # 适配项目名
      UWSGI_PROCESSES: 4
      UWSGI_THREADS: 2
    restart: always
    volumes:
      - static_volume:/gongjuyuan_chat/staticfiles
      - media_volume:/gongjuyuan_chat/media
      - ./db.sqlite3:/gongjuyuan_chat/db.sqlite3  # SQLite 数据库文件
    networks:
      - app_network


# 网络和卷配置
networks:
  app_network:
    driver: bridge

volumes:
  static_volume:    # 静态文件卷
  media_volume:     # 媒体文件卷
