# Generated by Django 4.2.5 on 2025-06-06 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_chatconversation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='应用名称')),
                ('description', models.TextField(blank=True, verbose_name='应用描述')),
                ('system_role', models.TextField(blank=True, help_text='设置AI助手的角色和行为', verbose_name='系统角色')),
                ('show_reasoning', models.BooleanField(default=False, verbose_name='显示思考过程')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.aimodel', verbose_name='使用的模型')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat.application', verbose_name='所属应用'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'is_active'], name='chat_applic_user_id_50db47_idx'),
        ),
    ]
