# Generated by Django 4.2.5 on 2025-06-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_application_chatconversation_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_public',
            field=models.BooleanField(default=False, help_text='公开的应用可以被所有用户查看和使用', verbose_name='是否公开'),
        ),
    ]
