# Generated by Django 4.2.5 on 2025-06-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_application_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='会话标识符'),
        ),
    ]
