# Generated by Django 4.2.5 on 2025-06-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_reasoning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='system_role',
            field=models.TextField(blank=True, default='你是一个智能助手，可以帮助用户解答问题。请保持友好和专业的态度。', help_text='设置AI助手的角色和行为', verbose_name='系统角色'),
        ),
    ]
