# Generated by Django 4.2.5 on 2025-06-08 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_alter_application_system_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='embedding_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'model_type': 'EMBEDDING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedding_applications', to='chat.aimodel', verbose_name='向量模型'),
        ),
        migrations.AddField(
            model_name='application',
            name='knowledge_similarity_threshold',
            field=models.FloatField(default=0.7, help_text='知识匹配的最小相似度阈值(0-1之间)', verbose_name='知识相似度阈值'),
        ),
        migrations.AddField(
            model_name='application',
            name='max_knowledge_items',
            field=models.IntegerField(default=3, help_text='每次对话最多使用的知识条数', verbose_name='最大知识条数'),
        ),
        migrations.AddField(
            model_name='application',
            name='use_knowledge_base',
            field=models.BooleanField(default=False, help_text='是否启用知识库功能', verbose_name='使用知识库'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
