# Generated by Django 4.2.5 on 2025-06-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0002_delete_modelparameter'),
        ('chat', '0008_application_embedding_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='embedding_model',
            field=models.ForeignKey(blank=True, help_text='选择用于知识库的向量模型', null=True, on_delete=django.db.models.deletion.SET_NULL, to='embeddings.embeddingmodel', verbose_name='向量模型'),
        ),
    ]
