# Generated by Django 4.2.5 on 2025-06-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_application_use_knowledge_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='knowledge_similarity_threshold',
            field=models.FloatField(default=0.5, help_text='知识匹配的最小相似度阈值(0-1之间)，建议设置为0.5-0.7之间', verbose_name='知识相似度阈值'),
        ),
    ]
