# Generated by Django 4.2.5 on 2025-06-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_application_knowledge_similarity_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='model',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.aimodel', verbose_name='使用的模型'),
        ),
    ]
