# Generated by Django 4.2.5 on 2025-06-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_application_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_public',
        ),
    ]
