# Generated by Django 4.2.5 on 2025-06-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_application_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='input_token_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=12, verbose_name='输入token单价(每百万token)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='output_token_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=12, verbose_name='输出token单价(每百万token)'),
        ),
    ]
