# Generated by Django 5.2 on 2025-06-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_aimodel_input_token_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='avatar',
            field=models.ImageField(blank=True, help_text='应用的头像图片，建议尺寸为200x200像素', null=True, upload_to='app_avatars/', verbose_name='应用头像'),
        ),
        migrations.AddField(
            model_name='application',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='应用的SVG图标代码，建议使用简单的单色图标', verbose_name='SVG图标'),
        ),
    ]
