# Generated by Django 4.2.5 on 2025-06-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('api_url', models.URLField(verbose_name='API地址')),
                ('api_key', models.CharField(max_length=255, verbose_name='API密钥')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型标识')),
                ('dimension', models.IntegerField(verbose_name='向量维度')),
                ('description', models.TextField(blank=True, verbose_name='模型描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('encoding_format', models.CharField(default='float', max_length=50, verbose_name='编码格式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '向量模型',
                'verbose_name_plural': '向量模型',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('value', models.TextField(verbose_name='参数值')),
                ('description', models.TextField(blank=True, verbose_name='参数描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='embeddings.embeddingmodel', verbose_name='所属模型')),
            ],
            options={
                'verbose_name': '模型参数',
                'verbose_name_plural': '模型参数',
                'ordering': ['model', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='知识内容')),
                ('embedding', models.BinaryField(verbose_name='向量嵌入')),
                ('similarity_score', models.FloatField(default=0.0, verbose_name='相似度分数')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embeddings.embeddingmodel', verbose_name='使用的模型')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('embedding', '向量化'), ('chat', '对话')], max_length=50, verbose_name='API类型')),
                ('request_data', models.JSONField(verbose_name='请求数据')),
                ('response_data', models.JSONField(verbose_name='响应数据')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('duration', models.FloatField(verbose_name='耗时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embeddings.embeddingmodel', verbose_name='使用的模型')),
            ],
            options={
                'verbose_name': 'API调用日志',
                'verbose_name_plural': 'API调用日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
