# Generated by Django 4.2.5 on 2025-06-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelParameter',
        ),
    ]
