# Generated by Django 4.2.5 on 2025-06-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0003_remove_knowledge_similarity_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledge',
            options={'ordering': ['-created_at'], 'verbose_name': '知识', 'verbose_name_plural': '知识'},
        ),
        migrations.RemoveField(
            model_name='embeddingmodel',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='embeddingmodel',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='embeddingmodel',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='embeddingmodel',
            name='encoding_format',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='embedding',
        ),
        migrations.AlterField(
            model_name='embeddingmodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embeddings.embeddingmodel', verbose_name='向量模型'),
        ),
        migrations.DeleteModel(
            name='APICallLog',
        ),
    ]
