# Generated by Django 4.2.5 on 2025-06-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0004_alter_knowledge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingmodel',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='API密钥'),
        ),
        migrations.AddField(
            model_name='embeddingmodel',
            name='dimension',
            field=models.IntegerField(default=1024, verbose_name='向量维度'),
        ),
        migrations.AddField(
            model_name='embeddingmodel',
            name='encoding_format',
            field=models.CharField(default='float', max_length=50, verbose_name='编码格式'),
        ),
    ]
