# Generated by Django 4.2.5 on 2025-06-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0005_embeddingmodel_api_key_embeddingmodel_dimension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingmodel',
            name='api_url',
            field=models.URLField(default=1, verbose_name='API地址'),
            preserve_default=False,
        ),
    ]
