# Generated by Django 4.2.5 on 2025-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0006_embeddingmodel_api_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='text',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='answer',
            field=models.TextField(default=1, verbose_name='答案'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='question',
            field=models.CharField(default=1, max_length=500, verbose_name='问题'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='knowledge',
            index=models.Index(fields=['question'], name='embeddings__questio_d6ec32_idx'),
        ),
    ]
