# Generated by Django 4.2.5 on 2025-06-06 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('model_type', models.CharField(choices=[('LLM', '大语言模型'), ('EMBEDDING', '向量模型'), ('ASR', '语音识别'), ('TTS', '语音合成'), ('RERANK', '重排模型'), ('VISION', '视觉模型'), ('IMAGE_GEN', '图片生成'), ('BASE', '基础模型')], max_length=20, verbose_name='模型类型')),
                ('api_url', models.URLField(blank=True, null=True, verbose_name='API地址')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.TextField(blank=True, verbose_name='模型描述')),
                ('max_tokens_limit', models.IntegerField(blank=True, help_text='该模型单次请求允许的最大token数', null=True, verbose_name='最大token限制')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'ordering': ['-created_at'],
            },
        ),
    ]
